# Generated by Django 5.0.6 on 2024-07-02 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apikeys',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('api_key', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('questions', models.IntegerField()),
                ('content', models.TextField()),
                ('date', models.CharField(max_length=40)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rubrics',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ensayos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('criteria', models.CharField(max_length=1000)),
                ('theme', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=500)),
                ('analysis', models.CharField(max_length=10000)),
                ('date', models.CharField(max_length=15)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('criteria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluador_openai.rubrics')),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sessions', models.IntegerField()),
                ('content', models.TextField()),
                ('date', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('criteria', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=100)),
                ('transcription', models.CharField(max_length=7500)),
                ('analysis', models.CharField(max_length=7500)),
                ('date', models.CharField(max_length=15)),
                ('criteria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluador_openai.rubrics')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
