# Generated by Django 5.0.6 on 2024-07-02 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluador_openai', '0002_rename_user_id_apikeys_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ensayos',
            old_name='user_id',
            new_name='user',
        ),
    ]
