# Generated by Django 5.0.6 on 2024-07-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluador_openai', '0003_rename_user_id_ensayos_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubrics',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
