# Generated by Django 5.0.6 on 2024-07-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluador_openai', '0004_alter_rubrics_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeys',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ensayos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='videos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
