# Generated by Django 5.0.6 on 2024-07-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluador_openai', '0005_alter_apikeys_id_alter_ensayos_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ensayos',
            old_name='path',
            new_name='file_name',
        ),
        migrations.AddField(
            model_name='ensayos',
            name='file',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
