# Generated by Django 5.0.6 on 2024-07-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluador_openai', '0006_rename_path_ensayos_file_name_ensayos_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensayos',
            name='file',
            field=models.FileField(upload_to='media/essays'),
        ),
    ]
