# Generated by Django 5.0.6 on 2024-07-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluador_openai', '0007_alter_ensayos_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ensayos',
            old_name='file',
            new_name='file_path',
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='path',
            new_name='file_name',
        ),
        migrations.AddField(
            model_name='videos',
            name='file_path',
            field=models.FileField(default=None, upload_to='media/videos'),
            preserve_default=False,
        ),
    ]
