# Generated by Django 5.0.6 on 2024-07-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluador_openai', '0009_rename_user_id_videos_user_alter_videos_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='file_path',
            field=models.CharField(max_length=200),
        ),
    ]
