# Generated by Django 5.0.6 on 2024-07-15 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluador_openai', '0011_questionnaire_topics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('criteria_name', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('analysis', models.TextField()),
                ('date', models.CharField(max_length=20)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluador_openai.rubrics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
