# Generated by Django 5.0.6 on 2024-10-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluador_openai', '0012_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='rda',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignments',
            name='file_path',
            field=models.FileField(upload_to='media/essays'),
        ),
    ]
